version: '3.3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    networks:
      - jaeger-network
  server:
    ports:
      - "8043:8043"
    build: .
    environment:
      ## optional: if provided, would be used as a configuration file
      - SOL_TO_UML__CONFIG=/app/config.toml
    env_file:
      ## optional: if provided, would overwrite values from configuration file
      - config/base.env
    volumes:
      ## optional: you can use default config or provide custom via file
      - ./config/base.toml:/app/config.toml
    networks:
      - jaeger-network
    depends_on:
      - jaeger

networks:
  jaeger-network:
