type: google.api.Service
config_version: 3

http:
  rules:
    - selector: blockscout.visualizer.v1.SolidityVisualizer.VisualizeContracts
      post: /v1/solidity:visualizeContracts
      body: "*"

    - selector: blockscout.visualizer.v1.SolidityVisualizer.VisualizeStorage
      post: /v1/solidity:VisualizeStorage
      body: "*"
